# Config file for https://pre-commit.com/#install
repos:
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.0  # Or the latest isort version
    hooks:
    -   id: isort
        args: ["--profile", "black"] # Recommended to align with Black's style
  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
        args: [--skip-string-normalization]
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        language_version: python3.10
