#!/bin/bash
# Template: This script is dynamically generated by the squash-commits skill.
# It replaces git's interactive rebase editor to automate squashing.
#
# Usage: GIT_SEQUENCE_EDITOR="./rebase-editor.sh" git rebase -i BASE
#
# The skill generates this script with the actual pick/fixup/exec commands
# based on the user-approved commit groupings.

set -euo pipefail

REBASE_TODO="$1"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
MESSAGES_DIR="${SCRIPT_DIR}/../.rebase-messages"

# Safety check: messages directory must exist
if [[ ! -d "$MESSAGES_DIR" ]]; then
    echo "ERROR: Messages directory not found: $MESSAGES_DIR" >&2
    echo "Run the squash-commits skill to generate commit messages first." >&2
    exit 1
fi

# The actual rebase todo content is generated by the skill and written below.
# Example format:
#
# cat > "$REBASE_TODO" << 'REBASE_EOF'
# pick abc1234 First commit of group 1
# fixup def5678 WIP commit
# fixup ghi9012 Another WIP
# exec git commit --amend -F .rebase-messages/01-feature-name.txt
#
# pick jkl3456 First commit of group 2
# fixup mno7890 WIP for group 2
# exec git commit --amend -F .rebase-messages/02-bugfix-name.txt
# REBASE_EOF

echo "ERROR: This is a template script. The skill should generate the actual content." >&2
exit 1
